"""add user id to spotify tokens

Revision ID: d624dde0f332
Revises: 31afd30694b3
Create Date: 2026-08-29 10:02:32.663596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd624dde0f332'
down_revision: Union[str, Sequence[str], None] = '31afd30694b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_tokens', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_spotify_tokens_user_id'), 'spotify_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spotify_tokens_user_id'), table_name='spotify_tokens')
    op.drop_column('spotify_tokens', 'user_id')
    # ### end Alembic commands ###
